/*
 * powerstage_app.c
 *
 *  Created on: 15 Mar 2026
 *      Author: jordan
 *
 *  Application state machine — Init → Running ↔ Fault
 *
 *  State descriptions:
 *
 *    INIT
 *      Runs once on the very first PS_App_Task() call.
 *      Probes I2C devices (EEPROM, OLED), loads/defaults config,
 *      initialises all sub-modules, starts ADC DMA, shows splash screen.
 *      Unconditionally transitions to RUNNING when complete.
 *
 *    RUNNING
 *      Normal operation at two periodic rates:
 *        MEASURE_INTERVAL_MS  — ADC readings, OC check, UV check
 *        BROADCAST_INTERVAL_MS — CAN broadcast of all status frames
 *      Also handles pending CAN RX commands every cycle.
 *      Transitions to FAULT when any ERR_xxx bit appears in error_code.
 *
 *    FAULT
 *      Same measurement and CAN handling as RUNNING, but:
 *        - UI state shown as SYS_FAULT (display cycles to fault page)
 *        - CAN broadcasts only state + voltage (minimal)
 *      Returns to RUNNING when all ERR_xxx bits are cleared.
 */

#include "powerstage_app.h"
#include "io_module.h"
#include "fan_ctrl.h"
#include "can_operation.h"
#include "eeprom_driver.h"
#include "ui_display.h"
#include "display_scheduler.h"
#include "ssd1306.h"
#include "fonts.h"
#include "battery.h"
#include <string.h>

/* ============================================================
 * External HAL handles (generated by CubeMX in main.c)
 * ============================================================ */
extern ADC_HandleTypeDef  hadc1;
extern I2C_HandleTypeDef  hi2c1;

/* ============================================================
 * Module config — loaded from EEPROM at startup
 * (public so CAN broadcasts can echo it)
 * ============================================================ */
Config g_config;

/* ============================================================
 * Public state flags
 * ============================================================ */
AppState_t g_app_state    = APP_STATE_INIT;
bool       g_oled_present  = false;
bool       g_eeprom_present = false;

/* ============================================================
 * Timing
 * ============================================================ */
#define MEASURE_INTERVAL_MS     100u    /* ADC / OC / UV check period   */
#define BROADCAST_INTERVAL_MS   500u    /* CAN broadcast period         */

static uint32_t s_measure_tick   = 0;
static uint32_t s_broadcast_tick = 0;

/* ============================================================
 * Private helpers
 * ============================================================ */

/* Apply loaded / defaulted config values to live module state */
static void Apply_Config(void)
{
    /* OC thresholds */
    for (uint8_t i = 0; i < CONFIG_RAIL_COUNT; i++) {
        oc_status.oc_threshold_mA[i] = g_config.oc_threshold_mA[i];
    }

    /* UV thresholds */
    uv_status.uv_V24_mV  = g_config.uv_V24_mV;
    uv_status.uv_VCAP_mV = g_config.uv_VCAP_mV;
    uv_status.uv_V12_mV  = g_config.uv_V12_mV;

    /* Fan defaults — update the fan_ctrl module instance */
    fan.Mode          = (fanMode_t)g_config.fan_default_mode;
    fan.min_dutycycle = g_config.fan_min_duty;
    fan.auto_on_temp  = g_config.fan_auto_on_temp;
    fan.auto_off_temp = g_config.fan_auto_off_temp;

    /* Actually drive the fan hardware to match the saved config */
    if (fan.Mode == FAN_ON) {
        fan_ctrl_on();
        fan_ctrl_speed(&fan, g_config.fan_default_duty);
    } else if (fan.Mode == FAN_ON_AUTO) {
        /* AUTO will be handled by FAN_AutoControl() each cycle;
         * just load the duty, don't force the fan on yet. */
        fan.dutycycle_pct = g_config.fan_default_duty;
    } else {
        fan_ctrl_off();
        fan.dutycycle_pct = g_config.fan_default_duty;
    }

    for (uint8_t i = 0; i < RAIL_COUNT; i++){
    	if((g_config.hs_default_state>>i)&0x01){
    		HS_Enable(&hotswap[i]);
    	}
    	else{
    		HS_Disable(&hotswap[i]);
    	}
    }

    /* OLED per-page dwell (Config.page_dwell[] = ticks per page; 0 = default). */
    for (uint8_t i = 0; i < CONFIG_PAGE_COUNT; i++) {
        UI_Display_SetPageDwell(i, g_config.page_dwell[i]);
    }

    /* SOC-low warning threshold (0 disables the warning). */
    Battery_SetLowSocThreshold_pct(g_config.bat_low_soc_pct);
}

/* Run all ADC-based measurements into the global `measurements` struct */
static void Run_Measurements(void)
{
    Bat_curr_measurement(&measurements);
    Cap_curr_measurement(&measurements);
    SBC_curr_measurement(&measurements);
    Drive_curr_measurement(&measurements);
    AUX_curr_measurement(&measurements);
    LED_curr_measurement(&measurements);
    V24_volt_measurement(&measurements);
    VCAP_volt_measurement(&measurements);
    V12_volt_measurement(&measurements);
    NTC_Temp_measurement(&measurements);

    /* SOC last — uses V24 + I_BAT computed above. The raw SOC is noisy
     * (V24/I sensor noise + transient load steps), so we feed it through
     * a smoothing filter with asymmetric hysteresis before broadcasting.
     * See Battery_FilterSOC_pct() in battery.c. */
    uint8_t raw_soc = Battery_EstimateSOC_pct(
        measurements.voltage_mV.V24,
        measurements.current_mA._currbat);
    measurements.battery_soc_pct = Battery_FilterSOC_pct(raw_soc);
}

/* Update OC fault / warning masks from live currents and HW FLT pins.
 * When a software OC threshold is exceeded the offending rail is
 * disabled immediately (latched until a CMD_OC_RESET clears it). */
static void Check_OC(void)
{
    const uint16_t currents[RAIL_COUNT] = {
        measurements.current_mA._curraux,
        measurements.current_mA._currled,
        measurements.current_mA._currdrive,
        measurements.current_mA._currcap,
        measurements.current_mA._currsbc
    };

    /* Hardware FLT pins — rebuild every cycle (active while FLT asserted) */
    oc_status.oc_fault_mask = 0;
    for (uint8_t i = 0; i < RAIL_COUNT; i++) {
        if (HS_Fault(&hotswap[i]))
            oc_status.oc_fault_mask |= (1u << i);
    }

    /* Software OC — latched: once set, stays until CMD_OC_RESET */
    for (uint8_t i = 0; i < RAIL_COUNT; i++) {
        if ((oc_status.oc_threshold_mA[i] > 0) &&
            (currents[i] > oc_status.oc_threshold_mA[i])) {
            oc_status.oc_warn_mask |= (1u << i);
            HS_Disable(&hotswap[i]);            /* shut down the rail */
        }
    }
}

/* Update UV fault mask from live voltages vs. active thresholds */
static void Check_UV(void)
{
    uv_status.uv_fault_mask = 0;

    if (measurements.voltage_mV.V24  < uv_status.uv_V24_mV)
        uv_status.uv_fault_mask |= UV_FAULT_V24;
    if (measurements.voltage_mV.VCAP < uv_status.uv_VCAP_mV)
        uv_status.uv_fault_mask |= UV_FAULT_VCAP;
    if (measurements.voltage_mV.V12  < uv_status.uv_V12_mV)
        uv_status.uv_fault_mask |= UV_FAULT_V12;
}

/* Consume pending CAN RX command flags set by the FDCAN ISR */
static void Handle_CAN_Commands(void)
{
    /* ── Fan ─────────────────────────────────────────────── */
    if (can_rxMessage.fan_cmd_received) {
        can_rxMessage.fan_cmd_received = 0;
        fan.Mode = (fanMode_t)can_rxMessage.fan_mode;

        /* Optional tuning fields, present only on the longer CMD_FAN forms.
         * Applied before the mode is acted on so a single frame can set a
         * threshold and select AUTO at the same time. */
        if (can_rxMessage.fan_cfg_valid) {
            fan.min_dutycycle = can_rxMessage.fan_min_duty;
            /* Hysteresis is only meaningful with on > off; a pair that does not
             * satisfy that would either chatter or latch, so it is rejected in
             * can_operation.c and never reaches here. */
            fan.auto_on_temp  = can_rxMessage.fan_auto_on_temp;
            fan.auto_off_temp = can_rxMessage.fan_auto_off_temp;
        }

        /* dutycycle_pct is what BCAST_FAN reports, and fan_ctrl_speed() is the
         * only thing that writes the timer compare - so it must never be
         * assigned directly. It used to be set unconditionally here, which made
         * FAN_OFF and FAN_ON_AUTO report a duty that had not been applied to
         * the hardware, and bypassed the min_dutycycle clamp on the way. */
        if (fan.Mode == FAN_ON) {
            fan_ctrl_on();
            fan_ctrl_speed(&fan, can_rxMessage.fan_duty);
        } else if (fan.Mode == FAN_OFF) {
            fan_ctrl_off();
            fan_ctrl_speed(&fan, 0);
        }
        /* FAN_ON_AUTO deliberately does nothing else: FAN_AutoControl() owns
         * the duty in that mode and sets it from temperature every cycle. */
    }

    /* ── HS switch enable/disable ────────────────────────── *
     * RAIL_SBC has no MCU-driven enable line on the PowerStage board —
     * its hot-swap is permanently configured by hardware. We skip it
     * here so the host can't accidentally believe it has control. */
    if (can_rxMessage.hs_cmd_received) {
        can_rxMessage.hs_cmd_received = 0;
        for (uint8_t i = 0; i < RAIL_COUNT; i++) {
            if (i == RAIL_SBC) continue;
            if (can_rxMessage.hs_state[i])
                HS_Enable(&hotswap[i]);
            else
                HS_Disable(&hotswap[i]);
        }
    }

    /* ── Overcurrent thresholds (CMD_OC) ─────────────────── *
     * RAIL_SBC has no MCU-driven EN — software OC stays disabled (=0). */
    if (can_rxMessage.oc_cmd_received) {
        can_rxMessage.oc_cmd_received = 0;
        oc_status.oc_threshold_mA[RAIL_AUX]   = can_rxMessage.oc_threshold_mA[RAIL_AUX];
        oc_status.oc_threshold_mA[RAIL_LED]   = can_rxMessage.oc_threshold_mA[RAIL_LED];
        oc_status.oc_threshold_mA[RAIL_DRIVE] = can_rxMessage.oc_threshold_mA[RAIL_DRIVE];
        oc_status.oc_threshold_mA[RAIL_CAP]   = can_rxMessage.oc_threshold_mA[RAIL_CAP];
    }

    /* ── Overcurrent fault reset (CMD_OC_RESET) ──────────── */
    if (can_rxMessage.oc_reset_received) {
        can_rxMessage.oc_reset_received = 0;
        uint8_t mask = can_rxMessage.oc_reset_mask & 0x0F;   /* AUX..CAP only */
        for (uint8_t i = 0; i < RAIL_COUNT; i++) {
            if (i == RAIL_SBC) continue;
            if (mask & (1u << i)) {
                if (oc_status.oc_warn_mask & (1u << i))
                    HS_Enable(&hotswap[i]);
                oc_status.oc_warn_mask  &= ~(1u << i);
                oc_status.oc_fault_mask &= ~(1u << i);
            }
        }
    }

    /* ── UV threshold update ─────────────────────────────── */
    if (can_rxMessage.uv_cmd_received) {
        can_rxMessage.uv_cmd_received = 0;
        uv_status.uv_V24_mV  = can_rxMessage.uv_V24_mV;
        uv_status.uv_VCAP_mV = can_rxMessage.uv_VCAP_mV;
        uv_status.uv_V12_mV  = can_rxMessage.uv_V12_mV;
    }

    /* ── EEPROM save ─────────────────────────────────────── */
    if (eeprom_cmd.write_eeprom_flag) {
        eeprom_cmd.write_eeprom_flag = 0;
        /* Snapshot live values into config before writing */
        g_config.fan_default_mode  = (uint8_t)fan.Mode;
        g_config.fan_default_duty  = fan.dutycycle_pct;
        g_config.fan_min_duty      = fan.min_dutycycle;
        g_config.fan_auto_on_temp  = fan.auto_on_temp;
        g_config.fan_auto_off_temp = fan.auto_off_temp;

        /* Snapshot current HS rail enable states */
        g_config.hs_default_state = 0;
        for (uint8_t i = 0; i < RAIL_COUNT; i++) {
            if (HAL_GPIO_ReadPin(hotswap[i].enable.port, hotswap[i].enable.pin) == GPIO_PIN_SET)
                g_config.hs_default_state |= (1u << i);
        }

        for (uint8_t i = 0; i < CONFIG_RAIL_COUNT; i++)
            g_config.oc_threshold_mA[i] = oc_status.oc_threshold_mA[i];
        g_config.uv_V24_mV  = uv_status.uv_V24_mV;
        g_config.uv_VCAP_mV = uv_status.uv_VCAP_mV;
        g_config.uv_V12_mV  = uv_status.uv_V12_mV;

        /* Snapshot live OLED page-dwell values */
        for (uint8_t i = 0; i < CONFIG_PAGE_COUNT; i++)
            g_config.page_dwell[i] = UI_Display_GetPageDwell(i);

        /* Snapshot live battery low-SOC warning threshold */
        g_config.bat_low_soc_pct = Battery_GetLowSocThreshold_pct();

        if (g_eeprom_present)
            EEPROM_Write_Config(1, 0, &g_config);
    }

    /* ── EEPROM load default ─────────────────────────────── */
    if (eeprom_cmd.reset_default_flag) {
        eeprom_cmd.reset_default_flag = 0;
        LoadDefault(&g_config);
        if (g_eeprom_present)
            EEPROM_Write_Config(1, 0, &g_config);
        Apply_Config();
    }

    /* ── GPIO / relay control ───────────────────────────── */
    if (can_rxMessage.ctrl_cmd_received) {
        can_rxMessage.ctrl_cmd_received = 0;
        HAL_GPIO_WritePin(V_LED_PWR_GPIO_Port, V_LED_PWR_Pin,
                          can_rxMessage.led_pwr_state ? GPIO_PIN_SET : GPIO_PIN_RESET);
        canstat.relay_enabled = (can_rxMessage.relay_state != 0);
    }

    /* ── OLED per-page dwell ─────────────────────────────── */
    if (can_rxMessage.page_dwell_cmd_received) {
        can_rxMessage.page_dwell_cmd_received = 0;
        for (uint8_t i = 0; i < CONFIG_PAGE_COUNT; i++) {
            UI_Display_SetPageDwell(i, can_rxMessage.page_dwell[i]);
        }
    }

    /* ── Battery SOC-low warning threshold ───────────────── */
    if (can_rxMessage.bat_cfg_cmd_received) {
        can_rxMessage.bat_cfg_cmd_received = 0;
        Battery_SetLowSocThreshold_pct(can_rxMessage.bat_low_soc_pct);
    }
}

/* ── Factory-reset button (PC13 / B1) ─────────────────────────────────────
 * Hold B1_Pin LOW for > 100 ms then release → erase all EEPROM pages.
 * Blocking — only triggered manually in the field.
 * ────────────────────────────────────────────────────────────────────────── */
static void Check_FactoryReset_Button(void)
{
    if (!HAL_GPIO_ReadPin(B1_GPIO_Port, B1_Pin)) {
        HAL_Delay(100);                                    /* debounce        */
        if (!HAL_GPIO_ReadPin(B1_GPIO_Port, B1_Pin)) {
            /* Button still held — wait for release then erase */
            while (!HAL_GPIO_ReadPin(B1_GPIO_Port, B1_Pin));
            for (int i = 0; i < 512; i++)
                EEPROM_pageErase(i);
        }
    }
}

/* ============================================================
 * Common task body — shared by RUNNING and FAULT states
 * ============================================================ */
static void Common_Task(void)
{
    uint32_t now = HAL_GetTick();

    /* ── Measurements + fault checks (every MEASURE_INTERVAL_MS) ── */
    if ((now - s_measure_tick) >= MEASURE_INTERVAL_MS) {
        s_measure_tick = now;
        Run_Measurements();
        Check_OC();
        Check_UV();
    }

    /* ── Fan control (every cycle — cheap GPIO/PWM update) ────────── */
    FAN_AutoControl(&fan, measurements.NTCTemperature_C);

    /* ── Handle pending CAN RX commands ───────────────────────────── */
    Handle_CAN_Commands();

    /* ── Sync display data (rebuilds error_code) ──────────────────── */
    UI_Display_UpdateFromModules(&measurements, &fan);

    /* ── CAN broadcasts (every BROADCAST_INTERVAL_MS) ─────────────── */
    if ((now - s_broadcast_tick) >= BROADCAST_INTERVAL_MS) {
        s_broadcast_tick = now;
        CAN_Broadcast_HS_State();
        CAN_Broadcast_HS_Current_A(&measurements);
        CAN_Broadcast_HS_Current_B(&measurements);
        CAN_Broadcast_Voltage(&measurements);
        CAN_Broadcast_Fan(&fan, measurements.NTCTemperature_C);
        CAN_Broadcast_EEPROM(&g_config);
        CAN_Broadcast_UV();
        CAN_Broadcast_OC_Config();
        CAN_Broadcast_IO_Status();
        CAN_Broadcast_Battery_Cfg();
    }

    /* ── Display scheduler ─────────────────────────────────────────── */
    if (g_oled_present)
        DisplayScheduler_Task();
}

/* ============================================================
 * State: INIT
 * Runs on the first PS_App_Task() invocation only.
 * ============================================================ */
static void State_Init(void)
{
    /* ── EEPROM probe + config load ──────────────────────────────── */
    g_eeprom_present = (HAL_I2C_IsDeviceReady(&hi2c1, 0xA0, 3, 500) == HAL_OK);
    if (g_eeprom_present) {
        EEPROM_Read_Config(1, 0, &g_config);
        if (!checkcfg(&g_config)) {
            /* First boot or corrupt — write factory defaults */
            LoadDefault(&g_config);
            EEPROM_Write_Config(1, 0, &g_config);
        }
    } else {
        LoadDefault(&g_config);
    }

    /* ── Hardware sub-modules ────────────────────────────────────── */
    HS_init();          /* DisableAll → 100 ms → EnableWithoutCap         */
    fan_init();         /* start TIM1 PWM, output = 0                     */
    Apply_Config();     /* push EEPROM values → oc_status / uv_status / fan */


    /* ── CAN ─────────────────────────────────────────────────────── */
    canstat.system_transmit_stat = true;
    CAN2_Host_Init();    /* Start FDCAN2 host bus with RX + relay      */

    /* ── ADC DMA — start once; continuous mode keeps it running ───── */
    HAL_ADC_Start_DMA(&hadc1, (uint32_t *)adc_buffer, ADC_CHANNELS);

    /* ── OLED probe + init ───────────────────────────────────────── */
    HAL_Delay(100);     /* let I2C bus settle after HS_init HAL_Delay    */
    g_oled_present = (HAL_I2C_IsDeviceReady(&hi2c1, 0x78, 3, 500) == HAL_OK);
    if (g_oled_present) {
        SSD1306_Init();
        UI_Display_Init();      /* shows "POWERSTAGE INIT" splash screen  */
        HAL_Delay(1000);        /* splash dwell                           */
        DisplayScheduler_Init();
    }

    /* ── Status LED: green = both I2C devices found ─────────────── */
    HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin,
                      (g_eeprom_present && g_oled_present)
                          ? GPIO_PIN_SET : GPIO_PIN_RESET);

    /* ── Initialise timing counters ─────────────────────────────── */
    s_measure_tick   = HAL_GetTick();
    s_broadcast_tick = HAL_GetTick();

    /* ── Transition ─────────────────────────────────────────────── */
    g_app_state = APP_STATE_RUNNING;
    UI_Display_SetState(SYS_RUNNING);
}

/* ============================================================
 * State: RUNNING — normal operation
 * ============================================================ */
static void State_Running(void)
{
    Common_Task();

    /* Transition to FAULT if any fault bit is active */
    if (display_data.error_code != ERR_NONE) {
        g_app_state = APP_STATE_FAULT;
        UI_Display_SetState(SYS_FAULT);
    }
}

/* ============================================================
 * State: FAULT — fault(s) active, monitor for recovery
 * ============================================================ */
static void State_Fault(void)
{
    Common_Task();

    /* Return to RUNNING once all faults have cleared */
    if (display_data.error_code == ERR_NONE) {
        g_app_state = APP_STATE_RUNNING;
        UI_Display_SetState(SYS_RUNNING);
    }
}

/* ============================================================
 * Public API
 * ============================================================ */

/* Call once in main() — after MX_xxx_Init() and AppInit() */
void PS_App_Init(void)
{
    CANInitTxHeader();
    /* Remaining init is deferred to State_Init() on first task call */
}

/* Call every main-loop cycle */
void PS_App_Task(void)
{
    FOCdetection();             /* Flash-over-CAN watchdog */
    Check_FactoryReset_Button();

    switch (g_app_state) {
        case APP_STATE_INIT:    State_Init();    break;
        case APP_STATE_RUNNING: State_Running(); break;
        case APP_STATE_FAULT:   State_Fault();   break;
        default:                g_app_state = APP_STATE_INIT; break;
    }
}
